# Generated by Django 2.0.5 on 2018-06-13 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0002_auto_20180613_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscore',
            old_name='part2',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='part1',
        ),
        migrations.AddField(
            model_name='userscore',
            name='part',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='voca.Part'),
            preserve_default=False,
        ),
    ]
