# Generated by Django 2.0.5 on 2018-06-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voca', '0003_auto_20180613_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='Set',
            new_name='testSet',
        ),
    ]
